# Change baseurl before deploy
baseURL: 'https://blog.himesamanoyume.top'

paginate: 5
defaultContentLanguage: en
languages:
  zh-cn:
    weight: 1
    params:
      linkedin: https://blog.himesamanoyume.top/zh-cn
  en:
    weight: 2
    params:
      linkedin: https://blog.himesamanoyume.top/en
    

menu:
  main:
    - name: 文章
      URL: /post
      weight: 1
    - name: 动态
      URL: /dynamic
      weight: 2
    - name: 笔记
      URL: /note
      weight: 3

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    endLevel: 4
    ordered: true
    startLevel: 2
  highlight:
    noClasses: false
    codeFences: true
    guessSyntax: true
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    tabWidth: 4